### ISSUE TITLE
False errors when asserting on enums

### ISSUE THREAD

**Issue by johan13** [aleclarson/spec.ts#4]
I would expect all four of these to pass, but two of them fail:

```ts
import { assert, _ } from "spec.ts";

enum Foo { Alpha, Beta }

const foo1      = Foo.Alpha;
let   foo2      = Foo.Alpha;
const foo3: Foo = Foo.Alpha;
const foo4      = Foo.Alpha as Foo;

assert(foo1, _ as Foo); // OK
assert(foo2, _ as Foo); // Not OK
assert(foo3, _ as Foo); // Not OK
assert(foo4, _ as Foo); // OK
```

I am using spec.ts 1.1.3 and Typescript 4.7.3 in strict mode.

**Comment by aleclarson** [comment]
This is a TypeScript bug (feature?).

If you mouse over `foo2` and `foo3` references (in the assert calls), you'll see their inferred type is `Foo.Alpha` which isn't the same as `Foo`.
